### PR TITLE
[FIX]: top nav highlight does not switch when using the back arrow

### LINKED ISSUE #444: Store top nav highlight does not switch when using the back arrow
### Describe the bug

After leaving the Epic Games Store via the back arrow the top nav highlight stays on Epic Games instead of moving to HyperPlay where the user currently is.

### Add logs

```
(13:21:17) INFO:    [Backend]:          Creating abort controller for legendary-version

(13:21:17) INFO:    [Legendary]:        Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary --version

(13:21:19) INFO:    [Backend]:          Creating abort controller for gogdl-version

(13:21:19) INFO:    [Gog]:              Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --version

(13:21:20) INFO:    [Backend]:          Creating abort controller for 98bc04bc842e4906993fd6d6644ffb8d

(13:21:20) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info

(13:21:20) INFO:    [Backend]:          Deleting abort controller for legendary-version

(13:21:21) INFO:    [Backend]:          Deleting abort controller for gogdl-version

(13:21:21) INFO:    [Legendary]:        installed.json updated, refreshing library

(13:21:22) INFO:    [Backend]:          Aborting 98bc04bc842e4906993fd6d6644ffb8d

(13:21:22) INFO:    [Backend]:          Aborted 98bc04bc842e4906993fd6d6644ffb8d

(13:21:22) INFO:    [Legendary]:        Abort command "C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"

(13:21:22) INFO:    [Backend]:          Deleting abort controller for 98bc04bc842e4906993fd6d6644ffb8d

(13:21:22) INFO:    [Backend]:          Creating abort controller for 98bc04bc842e4906993fd6d6644ffb8d

(13:21:22) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info

(13:21:23) INFO:    [Backend]:          Aborting 98bc04bc842e4906993fd6d6644ffb8d

(13:21:23) INFO:    [Backend]:          Aborted 98bc04bc842e4906993fd6d6644ffb8d

(13:21:23) INFO:    [Legendary]:        Abort command "C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"

(13:21:23) INFO:    [Backend]:          Deleting abort controller for 98bc04bc842e4906993fd6d6644ffb8d

(13:21:32) INFO:    [Backend]:          Creating abort controller for legendary-version

(13:21:32) INFO:    [Legendary]:        Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary --version

(13:21:32) INFO:    [Backend]:          Creating abort controller for gogdl-version

(13:21:32) INFO:    [Gog]:              Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --version

(13:21:32) INFO:    [Backend]:          Creating abort controller for 98bc04bc842e4906993fd6d6644ffb8d

(13:21:32) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info

(13:21:33) INFO:    [Backend]:          Deleting abort controller for gogdl-version

(13:21:33) INFO:    [Backend]:          Deleting abort controller for legendary-version

(13:21:33) INFO:    [Backend]:          Aborting 98bc04bc842e4906993fd6d6644ffb8d

(13:21:33) INFO:    [Backend]:          Aborted 98bc04bc842e4906993fd6d6644ffb8d

(13:21:33) INFO:    [Legendary]:        Abort command "C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"

(13:21:33) INFO:    [Backend]:          Deleting abort controller for 98bc04bc842e4906993fd6d6644ffb8d

(13:21:33) INFO:    [Backend]:          Creating abort controller for 98bc04bc842e4906993fd6d6644ffb8d

(13:21:33) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info

(13:21:34) INFO:    [Backend]:          Aborting 98bc04bc842e4906993fd6d6644ffb8d

(13:21:34) INFO:    [Backend]:          Aborted 98bc04bc842e4906993fd6d6644ffb8d

(13:21:34) INFO:    [Legendary]:        Abort command "C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"

(13:21:34) INFO:    [Backend]:          Deleting abort controller for 98bc04bc842e4906993fd6d6644ffb8d
```

### Steps to reproduce

1. Observe top nav highlight on "HyperPlay"
2. Click "Epic Games" top nav
3. Observe top nav highlight on "Epic Games"
4. Click the back arrow to return to previous page
5. Observe top nav highlight is still on "Epic Games"

### Expected behavior

Top nav highlight should move to the current page

### Screenshots

image

### hyperplay Version

Latest Stable

### System Information

- Windows
- hyperplay Version 0.4.2 and 0.5.0

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by eliobricenov**
## Summary
This is a tricky one. After debugging, I found the root cause: When users click on the back arrow, they don't actually leave the current route, they remain in the same one but navigate inside the `webview` to the previous page, which happens to be the Hyperplay store. The navbar highlighting doesn't change because the route doesn't change.

In this approach, I used [canGoToOffset](https://www.electronjs.org/docs/latest/api/webview-tag#webviewcangotooffsetoffset) to check if the users can navigate **two** levels up in the history. Because the initial previous page (offset -1)  seems to be always the Hyperplay store if `canGoToOffset(-2)` is `false`, the current page can only return to the Hyperplay store page, and we do `navigate('/')` instead of `webview.goBack()`

I **don't** love this approach because it hardcodes the controller's behavior to always go to the homepage as the "exit" behavior via the black arrow.

## Checks
- [ ] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [x] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

closes #444

### CODE REVIEW

File: src/frontend/components/UI/WebviewControls/index.tsx [hunk 1]
```diff
@@ -66,6 +68,10 @@ export default function WebviewControls({
           return webview?.reload()
         }
         if (event === 'back') {
+          // if the user is on the first page, offset -1 will be hyperplay store
+          // and -2 will be the undefined page
+          const isFirstPage = webview?.canGoToOffset(-2)
+          if (!isFirstPage) return navigate('/')
```
Comment (BrettCleary) [inline src/frontend/components/UI/WebviewControls/index.tsx:74]: this will fail if we:
1. go to hp store
2. go to epic store
3. go to gog
4. click back which will take us to epic store but gog will still be highlighted since we never navigated there

we need to listen to the webview element for when it navigates and use that url 

adding the following to src/frontend/screens/WebView/index.tsx will work
```
webview.addEventListener('did-navigate', (ev) =>
        console.log('did navigate ', ev.url)
      )
```

Comment (BrettCleary) [reply src/frontend/components/UI/WebviewControls/index.tsx:74]: maybe instead of using the pathname and search params in `TopNavBar` we could use a mobx store that is updated with the url that the webview is navigated to?

**Review by BrettCleary — COMMENTED** [review]
see attached comments

File: src/frontend/components/UI/WebviewControls/index.tsx (hunk 1 above)
Comment (eliobricenov) [reply src/frontend/components/UI/WebviewControls/index.tsx:74]: Oh that’s a great call, we could use persisted value to render the styles only.

**Review by flavioislima — COMMENTED** [review]
Looks pretty good!  
left one small comment only 👍🏽

**Comment by nyghtstalker** [comment]
- Start at Library (or any page that isn't the store -> go store -> click into any game -> press the back button on the mouse -> user is taken to the library instead of back to the store page.

This functionality is working correctly in the library so just copy it from that to the store.

File: src/common/types.ts [hunk 2]
```diff
@@ -564,20 +567,7 @@ interface GamepadActionArgsWithoutMetadata {
...
-  reload: () => void
-  isLoading: () => boolean
-  getURL: () => string
-  copy: () => string
-  selectAll: () => void
-  findInPage: (text: string | RegExp) => void
-}
-
-export type WebviewType = HTMLWebViewElement & ElWebview
+export type WebviewType = HTMLWebViewElement & WebviewTag
```
Comment (BrettCleary) [inline src/common/types.ts:570]: We can get rid of this line and just import `WebviewTag` directly wherever we need it. It inherits from `HTMLElement` the same as HTMLWebViewElement

File: src/common/types.ts [hunk 3]
```diff
@@ -564,20 +567,7 @@ interface GamepadActionArgsWithoutMetadata {
...
-  canGoForward: () => boolean
-  goBack: () => void
-  goForward: () => void
-  reload: () => void
-  isLoading: () => boolean
-  getURL: () => string
-  copy: () => string
-  selectAll: () => void
-  findInPage: (text: string | RegExp) => void
-}
```
Comment (BrettCleary) [inline src/common/types.ts:578]: nice!

File: src/frontend/__tests__/helpers/extract-main-domain.test.ts [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+    expect(mainDomain).toEqual('example.com')
+  })
+
+  it('return null when url is invalid', () => {
+    jest.spyOn(console, 'error').mockImplementationOnce(jest.fn)
+    const url = 'invalid url'
+    const mainDomain = extractMainDomain(url)
+    expect(mainDomain).toEqual(null)
+  })
+})
```
Comment (BrettCleary) [inline src/frontend/__tests__/helpers/extract-main-domain.test.ts:34]: :fire: :fire: :fire:

File: src/frontend/helpers/extract-main-domain.ts [hunk 5]
```diff
@@ -0,0 +1,15 @@
...
+    const domain = new URL(url).hostname
+    const parts = domain.split('.')
+
+    if (parts.length >= 2) {
+      return parts.slice(-2).join('.')
+    }
+
+    return domain
+  } catch (e) {
+    console.error(e)
```
Comment (BrettCleary) [inline src/frontend/helpers/extract-main-domain.ts:12]: could we change this to a console warn and also log the url that it was called with as well. 

this is what I get on first app launch 
image

**Review by BrettCleary — CHANGES_REQUESTED** [review]
nice work! left some small comments, but the core functionality is working nicely now

**Comment by BrettCleary** [comment]
also can you address this error message as well
image

**Comment by BrettCleary** [comment]
if you go to the game page and click "store page" in the drop down, it will navigate to the store but the top nav bar items won't appear 

I recently changed some code in the Webview module on this PR https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/pull/453 so that might fix as well

image

image

**Comment by eliobricenov** [comment]
> also can you address this error message as well image

Done. This was caused because `makeObservable()` was being called in the `init()` from the inherited class instead of the `constructor`, idk why I did that tbh 😅

File: src/frontend/helpers/extract-main-domain.ts (hunk 5 above)
Comment (eliobricenov) [reply src/frontend/helpers/extract-main-domain.ts]: yes. I added an early return too in the `getStyles` function to avoid spamming the console with warnings

File: src/frontend/screens/WebView/index.tsx [hunk 6]
```diff
@@ -35,29 +45,23 @@ export default function WebView() {
...
-  const wikiURL = 'https://docs.hyperplaygaming.com/'
+  const epicStoreUrlWithLanguage = `${EPIC_STORE_URL}/${lang}/`
   const gogEmbedRegExp = new RegExp('https://embed.gog.com/on_login_success?')
-  const gogLoginUrl =
-    'https://auth.gog.com/auth?client_id=46899977096215655&redirect_uri=https%3A%2F%2Fembed.gog.com%2Fon_login_success%3Forigin%3Dclient&response_type=code&layout=galaxy'
 
   const trueAsStr = 'true' as unknown as boolean | undefined
   const { runner } = useParams() as { runner: Runner }
 
   const urls = {
```
[the remark this answers is not in the document]
Comment (eliobricenov) [reply src/frontend/screens/WebView/index.tsx:60]: Do you mean`gogEmbedRegExp`?  `gogLoginUrl` is already in the constant file. We can add `gogEmbedRegExp` too, though. I think it is worth adding a new `GOG_EMBED_URL` constant that is used to create the regex.

**Comment by eliobricenov** [comment]
> if you go to the game page and click "store page" in the drop down, it will navigate to the store but the top nav bar items won't appear
> 
> this is also broken here #453 but would be best handled on this `nav-highlight` branch.
> 
> * I did fix the missing `?isLauncher=true` queryparam on this page though on 453 so don't worry about that on this branch
> 
> image
> 
> image

@BrettCleary The reason why this is happening is that when "Store Page" is clicked we go to the `/store-page` route which is not set as a [page to show nav options](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/blob/main/src/frontend/components/UI/TopNavBar/index.tsx#L20-L25). Do we want to add it?

File: src/frontend/constants.ts [hunk 7]
```diff
@@ -0,0 +1,9 @@
+export const EPIC_LOGIN_URL = 'https://legendary.gl/epiclogin'
+export const HYPERPLAY_STORE_URL = 'https://store.hyperplay.xyz?isLauncher=true'
+export const EPIC_STORE_URL = 'https://www.epicgames.com/store'
+export const GOG_STORE_URL = `https://gog.com`
+export const WIKI_URL = 'https://docs.hyperplaygaming.com/'
+export const GOG_LOGIN_URL =
+  'https://auth.gog.com/auth?client_id=46899977096215655&redirect_uri=https%3A%2F%2Fembed.gog.com%2Fon_login_success%3Forigin%3Dclient&response_type=code&layout=galaxy'
+
+export const GOG_EMBED_URL = 'https://embed.gog.com/on_login_success?'
```
[the remark this answers is not in the document]
Comment (eliobricenov) [reply src/frontend/constants.ts:9]: Not really sure what to do here, it is the same string 😅

File: src/frontend/screens/WebView/index.tsx (hunk 6 above)
[the remark this answers is not in the document]
Comment (eliobricenov) [reply src/frontend/screens/WebView/index.tsx:60]: It looks like it is insecure to use a string variable of a hostname for a regex https://codeql.github.com/codeql-query-help/go/go-incomplete-hostname-regexp/. Let's keep `gogEmbedRegExp`

**Review by BrettCleary — APPROVED** [review]
LGTM! nice work! :fire:

**Review by nyghtstalker — APPROVED** [review]
