### PR TITLE
[FIX] Deal with Epic games listing from Quests Page

### LINKED ISSUE #990: Epic forwarding games are added directly to library when navigating through the Quests tab
### Describe the bug

User are able to add Epic forwarding games to their library via the Quests tab. 

### Add logs

N/A

### Steps to reproduce

1. Go to the store game page for Apeiron
2. Observe that it is Epic forwarding (Download on Epic)
3. Go to the Quests tab
4. Select "Game7 Credits" Apeiron" quest
5. Click View Game
6. Observe that the user is taken to the "HyperPlay" version of Apeiron and not the Epic game

### Expected behavior

Need to figure out the best way to handle "View Game" for quests that have Epic forwarding games

### Screenshots

image
image
image
image

### hyperplay Version

Latest Stable

### System Information

- Windows 10
- hyperplay Version 0.17.2

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by flavioislima**
FIX #990 by  adding some methods to get the epic url from the API and checking it with the epic games on the use library then navigating either to the library page (when the game is on the library) or to the epic games store page.

---

Use the following Checklist if you have changed something on the Backend or Frontend:

- [x] Tested the feature and it's working on a current and clean install.
- [ ] Tested the main App features and they are still working on a current and clean install. (Login, Install, Play, Uninstall, Move games, etc.)
- [ ] Created / Updated Tests (If necessary)
- [ ] Created / Updated documentation (If necessary)

### CODE REVIEW

File: src/backend/storeManagers/hyperplay/library.ts [hunk 1]
```diff
@@ -46,6 +47,38 @@ export async function addGameToLibrary(projectId: string) {
   hpLibraryStore.set('games', [...currentLibrary, gameInfo])
 }
 
+// hit the valist api and get the info if the game is a epic listing
+export async function getEpicListingUrl(projectId: string): Promise<string> {
```
Comment (BrettCleary) [inline src/backend/storeManagers/hyperplay/library.ts:51]: I think this should be in `src\backend\storeManagers\hyperplay\utils.ts` since we try to keep the store manager library and games modules' api's 1:1 with all the other stores

File: src/frontend/helpers/index.ts [hunk 2]
```diff
@@ -148,6 +149,41 @@ export function getPlatformName(platform: string): string {
   }
 }
 
+const getLastPartOfUrl = (url: string) => {
+  return url.split('/').pop()
+}
+
+export const fetchEpicListing = async (projectId: string) => {
```
Comment (BrettCleary) [inline src/frontend/helpers/index.ts:156]: we'll just need to remember to qa this for new epic game forwarder listings since developers could enter an epic url that might break this

File: src/frontend/screens/Quests/components/QuestDetailsViewPlay/index.tsx [hunk 3]
```diff
@@ -36,11 +37,38 @@ export function QuestDetailsViewPlayWrapper({
...
-      navigate(`/gamepage/hyperplay/${appName}`, {
-        state: { gameInfo, fromDM: false }
-      })
+      const { appName: epicAppName, epicListingUrl } = await fetchEpicListing(
+        appName
+      )
+      const runner: Runner = epicListingUrl ? 'legendary' : 'hyperplay'
+
+      // check for gameinfo to see if it is on the library
+      return getGameInfo(epicAppName || appName, runner)
```
Comment (BrettCleary) [inline src/frontend/screens/Quests/components/QuestDetailsViewPlay/index.tsx:46]: can we set these in the same if statement like
```
let runner = 'hyperplay'
let name = appName
if (epicListingUrl && epicAppName){
  runner = 'legendary
  name = epicAppName
}
```

otherwise if `fetchEpicListing` returns empty string for appName but a correct epic listing url, it would try to navigate to the 'hyperplay' runner with the epic app name

File: src/frontend/screens/Quests/components/QuestDetailsViewPlay/index.tsx [hunk 4]
```diff
@@ -36,11 +37,38 @@ export function QuestDetailsViewPlayWrapper({
...
+        .then((res) => {
+          if (!res) {
+            throw new Error('Game not found in library')
+          }
+
+          return navigate(
+            `/gamepage/${runner}/${epicAppName ? epicAppName : appName}`,
```
Comment (BrettCleary) [inline src/frontend/screens/Quests/components/QuestDetailsViewPlay/index.tsx:53]: can reference the same variable for app name here too

**Review by BrettCleary — COMMENTED** [review]
I am unable to launch this branch in dev mode

I get this error `Cannot use 'in' operator to search for 'CallExpression' in undefined`

File: src/frontend/screens/Quests/components/QuestDetailsViewPlay/index.tsx
Comment (BrettCleary) [inline src/frontend/screens/Quests/components/QuestDetailsViewPlay/index.tsx:1]: I think  the logic you added for navigation here could be abstracted away to a hook too so that we can reuse this functionality elsewhere on the frontend

**Review by BrettCleary — APPROVED** [review]
It works but I get 100's of lines logged to the console on click. it logs an axios response after

```
(15:06:55) ERROR:   [Legendary]:        Error Getting Info from Epic API
(15:06:55) ERROR:   [Legendary]:        AxiosError: Request failed with status code 403
... 100's of lines of axios response logs
```

we should clean up this logging

**Comment by nyghtstalker** [comment]
**-- When the user IS logged into EPIC:**

I believe it was the initial attempt to install the game from the quests page I got this warning on the install modal

image

However, after every other attempt, I could not replicate this and this warning doesn't appear again.

Aperion is the only game in quests, atm, that has an EPIC forward. The user is now taken to the EPIC game page instead of the HP game page. 


**-- When the user IS NOT logged into EPIC:**

Clicking the game via the quests page now takes the user to the Epic Store game page.

image

With this flow the user needs to have (or will need to create) an EPIC account and then log into the account via HP in order to play it. Once the user is logged in the user will need to know how to access/install the game since this store page does not trigger a download or take the user to the install page. 

At this point once the user adds the game to their EPIC library they have to wait for it to appear in their EPIC library and then find and install it via the EPIC page in the Library. To my knowledge this is the only way to access an EPIC game. It is fairly complicated and if the user does not know what to do it is very difficult.

With all that being said...I feel the best option is to either now allow EPIC forward games to have quests (since this is process is complicated and I think it will cause user frustration) OR they need to have a version uploaded to HP (which I think nearly every game does submit one via the review process) and they use that version instead of forwarding to EPIC.

I know this is a lot but I think this needs to get addressed and figured out to help improve the user experience. @BrettCleary @flavioislima @awantoch

**Comment by BrettCleary** [comment]
@flavioislima is there a way we can programmatically add an epic game to the user's library with legendary? we can handle on a separate branch/issue but I think this would address @nyghtstalker's concerns. curious if it's possible.

To your point @nyghtstalker, Heroic has been using this pattern for a long time, and while steps can be consolidated, it should work for now. We will always be able to provide better support for games directly on HP store and game devs understand that.

**Comment by flavioislima** [comment]
@nyghtstalker 

1. This one was a false positive, might happens from time to time, not related with the PR. If the user clicks install and they had permission it will work just fine. i can double check this method on another PR later.
2. Unfortunately there is not much we can do about it to improve this workflow. The Epic integration is implemented as it is and we only read the list of games the user already has in their library. to make it worse it might take a few minutes for the game to appear on HyperPlay library and sometimes even a restart. In this matter we are pretty limited.
3. About quests for Epic games this should be something we need to discuss for sure, or find ways of improving the flow by adding this type of information/instructions to the quest itself. Let's bring that to our next team meeting.
4. @BrettCleary Legendary only reads information from Epic, there is not way to add a game to the user library without going through the Epic website. Even for free games we need to go through their carting system. In Heroic there were some researches on how to add the weekly free game to the user library but without much success.

File: src/frontend/helpers/index.ts (hunk 2 above)
Comment (flavioislima) [reply src/frontend/helpers/index.ts:156]: Yes. The only way to make this 100% reliable would be to have the Epic `appName` in the dev portal. For every new listing with quests we will need to double check this and even adjust it.

File: src/frontend/screens/Quests/components/QuestDetailsViewPlay/index.tsx (hunk 3 above)
Comment (flavioislima) [reply src/frontend/screens/Quests/components/QuestDetailsViewPlay/index.tsx:46]: Good call

File: src/backend/storeManagers/hyperplay/library.ts (hunk 1 above)
Comment (flavioislima) [reply src/backend/storeManagers/hyperplay/library.ts:51]: done

File: src/frontend/screens/Quests/components/QuestDetailsViewPlay/index.tsx (hunk 3 above)
Comment (flavioislima) [reply src/frontend/screens/Quests/components/QuestDetailsViewPlay/index.tsx:46]: Ok, after changing it stoppeed working and now I remember why I did this way. It is because for the last case (navigate to epic store) we need it to be runner legendary BUT has an epic listing as well.
but I can adjust this logic.

**Review by jiyuu-jin — APPROVED** [review]

**Review by nyghtstalker — APPROVED** [review]
@flavioislima @BrettCleary Thank you both for all the feedback. I def agree that we need to figure out the best flow for a better experience with all this.  I will make a card to help track for an improvement on this. This PR is working as intended and I won't let this hold it up. Great job on this, sir!
